# Generated by Django 2.2 on 2020-07-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200720_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='address',
            field=models.CharField(db_index=True, default='en', max_length=500, verbose_name='address'),
        ),
    ]
