# Generated by Django 2.2 on 2020-07-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200720_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_country', to='home.Countries'),
        ),
    ]
