# Generated by Django 2.2 on 2020-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='level_choices',
            new_name='level',
        ),
    ]
