# Generated by Django 2.2 on 2020-06-07 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_courserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.FloatField(choices=[('ONE', 1), ('OND_AND_HALF', 1.5), ('TWO', 2), ('TWO_AND_HALF', 2.5), ('THREE', 3), ('THRE EAND_HALF', 3.5), ('FOUR', 4), ('FOR AND_HALF', 4.5), ('FIVE', 5)], default=0),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
