# Generated by Django 2.2 on 2020-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_instructorrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content_summary',
            field=models.TextField(blank=True, verbose_name='content_summary'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Levels', 'All Levels')], default='All Levels', max_length=50, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='review',
            field=models.TextField(verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='instructorrating',
            name='review',
            field=models.TextField(verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='review',
            field=models.TextField(verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
