# Generated by Django 2.2 on 2020-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200626_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='courserating',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='instructorrating',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='profiles',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='text',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
    ]
