# Generated by Django 2.2 on 2020-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200627_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='courserating',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='instructorrating',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='profiles',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='text',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
    ]
