# Generated by Django 2.2 on 2020-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200706_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.FloatField(default=5),
        ),
    ]
