# Generated by Django 2.2 on 2020-07-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_module_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
