# Generated by Django 2.2 on 2020-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='braintree_id',
            new_name='pan_id',
        ),
    ]
