# Generated by Django 2.2 on 2020-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200621_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='client_id',
            field=models.IntegerField(db_index=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
    ]
